/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RTD.h"
#include "IDAC8_1.h"
#include "CurrentMux.h"
#include "ADC_DelSig_1.h"
#include "ADCMux.h"
#include "UART_1.h"
#include "RTD_Current_aliases.h"
#include "RTD_Current.h"
#include "R_ref_current_aliases.h"
#include "R_ref_current.h"
#include "RTD_positive_aliases.h"
#include "RTD_positive.h"
#include "RTD_negative_aliases.h"
#include "RTD_negative.h"
#include "R_ref_positive_aliases.h"
#include "R_ref_positive.h"
#include "R_ref_negative_aliases.h"
#include "R_ref_negative.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_1_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

